---
outlines:
    default:       { width: 54,  height: 42 }
    altline:       { width: 81,  height: 42 }
    wide:          { width: 100, height: 42 }
    change-view:   { width: 81,  height: 42 }
    change-view-2: { width: 100, height: 42 }
    spaceline:     { width: 205, height: 42 }
    special:       { width: 54,  height: 42 }

views:
    base:
        - "a z e r t y u i o p"
        - "q s d f g h j k l m"
        - "Shift_L   w x c v b n '   BackSpace"
        - "show_numbers show_eschars ,     space      . Return"
    upper:
        - "A Z E R T Y U I O P"
        - "Q S D F G H J K L M"
        - "Shift_L   W X C V B N @  BackSpace"
        - "show_numbers (         space    ) . Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # € $ % & - _ + *"
        - "show_symbols   , \" ' : ; ! ?  BackSpace"
        - "show_letters (        space     ) . Return"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ $ ¥ ^ ° * { }"
        - "show_numbers_from_symbols   \\ / < > = [ ]  BackSpace"
        - "show_letters (        space      ) . Return"
    eschars:
        - "à â é è ê û ù î ô ç"
        - "À Â É È Ê Û Ù Î Ô Ç"
        - "Ctrl  æ œ ä ë ï ö ü  BackSpace"
        - "show_letters (         space     ) . Return"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "wide"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "*/="
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "altline"
        label: "âÂ"
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "wide"
        icon: "key-enter"
        keysym: "Return"
    Ctrl:
        modifier: "Control"
        outline: "small"
        label: "Ctrl"

